# Generated by Django 4.2 on 2024-09-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True, verbose_name='Имя пользователя')),
                ('first_login', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации пользователя')),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип буста')),
                ('description', models.TextField(verbose_name='Описание буста')),
                ('date_of_receipt', models.DateTimeField(auto_now=True, verbose_name='Дата получения')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_profile.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Буст',
                'verbose_name_plural': 'Бусты',
            },
        ),
    ]
